### ISSUE TITLE
in 1.39.3v can't open chests when I use no damage 

### ISSUE THREAD

**Issue by mrmr44** [kindawindytoday/Minty-Releases#18]

**Comment by WQ3465802** [comment]
me too

**Comment by BeSsswss** [comment]
This is a noclip problem, not no damage

**Comment by Ruk-khadevata** [comment]
After turning on the game once using noclip: sprint stops working, glider flight and charged attack either does not work "F" with almost everything in the world or all items at once. The crutch solution to this problem is to go to the initial menu and start the game again, then "F" works with the world but does not fix the rest of the items

written with the help of a translator

После включения игры один раз используя noclip: перестает работать спринт, полет на глайдере и заряженная атака либо не работает "F" практически со всем в мире или все пункты сразу. Костыльное решение данной проблемы это выйти в начальное меню и снова запустить игру, тогда "F" с миром работает но не чинит остальные пункты
